@Host = http://localhost:5000


POST {{Host}}/api/users/register
Content-Type: application/json
Accept: application/json

{
    "email" : "sallam@gmail.com",
    "firstName":"Abdulrahman",
    "lastName":"Sallam",
    "password":"12345"
}

##